'use strict';

/**
 * Integration tests for the canary shadow runner + auto-promotion pipeline.
 *
 * AC coverage (specs/auto-evolving-bash-filters.md):
 *   specs/auto-evolving-bash-filters.md#AC-1  — dispatch() template resolution (via df-bash-rewrite test suite, exercised here via hook subprocess)
 *   specs/auto-evolving-bash-filters.md#AC-2  — ≥8 archetype templates present (covered by templates.test.js; hook calls them here)
 *   specs/auto-evolving-bash-filters.md#AC-3  — structured output schema per template (covered by templates.test.js)
 *   specs/auto-evolving-bash-filters.md#AC-4  — PROTECTED list + DF_BASH_REWRITE=0 (covered by df-bash-rewrite.test.js; end-to-end verified here)
 *   specs/auto-evolving-bash-filters.md#AC-5  — df-bash-telemetry JSONL row per invocation (covered by df-bash-telemetry.test.js)
 *   specs/auto-evolving-bash-filters.md#AC-6  — df-filter-suggest ranked table, N≥5 gate (covered by bin/df-filter-suggest tests)
 *   specs/auto-evolving-bash-filters.md#AC-7  — --propose mode writes filters-proposed.yaml (covered by bin/df-filter-suggest tests)
 *   specs/auto-evolving-bash-filters.md#AC-8  — canary latency <5ms p95 delta; promotion at ≥20 rows; non-promotion at 19 rows
 *   specs/auto-evolving-bash-filters.md#AC-9  — normalization unit tests (covered by lib/filter-dispatch.test.js)
 *   specs/auto-evolving-bash-filters.md#AC-10 — gitignore entries for telemetry + canary logs (covered by ac-coverage.test.js)
 *
 * Primary focus: specs/auto-evolving-bash-filters.md#AC-8 end-to-end integration.
 *
 * Test 1 — latency (50 runs, p95 delta < 5ms)
 * Test 2 — promotion path: 20 clean canary rows → proposal promoted to generated/
 * Test 3 — non-promotion: 19 rows → proposal stays in filters-proposed.yaml unchanged
 */

const { test, describe, before, after, beforeEach, afterEach } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { execFileSync, spawnSync } = require('node:child_process');

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const WORKTREE_ROOT = path.resolve(__dirname, '..');
const HOOK_PATH     = path.resolve(__dirname, 'df-bash-rewrite.js');
const SUGGEST_PATH  = path.resolve(WORKTREE_ROOT, 'bin', 'df-filter-suggest.js');
const TEMPLATES_DIR = path.resolve(__dirname, 'filters', 'templates');
const GENERATED_DIR = path.resolve(__dirname, 'filters', 'generated');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeTmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'df-integration-test-'));
}

function rmrf(dir) {
  if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
}

/**
 * Compute p95 of an array of numbers (must be non-empty).
 * Sort ascending; take the item at ceil(N * 0.95) - 1.
 */
function p95(arr) {
  const sorted = [...arr].sort((a, b) => a - b);
  const idx = Math.ceil(sorted.length * 0.95) - 1;
  return sorted[idx];
}

/**
 * Run the df-bash-rewrite hook once with the given command and return
 * the wall-clock nanoseconds elapsed (BigInt converted to number as ms float).
 */
function measureHookMs(cmd, cwd) {
  const input = JSON.stringify({
    tool_name: 'Bash',
    tool_input: { command: cmd },
    cwd,
  });

  const start = process.hrtime.bigint();
  try {
    execFileSync(process.execPath, [HOOK_PATH], {
      input,
      cwd,
      encoding: 'utf8',
      timeout: 10_000,
      env: { ...process.env, DF_BASH_REWRITE: undefined },
    });
  } catch (_) {
    // hook may produce no output for some commands — that is fine
  }
  const end = process.hrtime.bigint();
  return Number(end - start) / 1_000_000; // ns → ms
}

/**
 * Build the minimal proposals YAML understood by both parseProposalsYaml
 * implementations (df-bash-rewrite.js and df-filter-suggest.js).
 */
function buildProposalYaml(template, pattern, score) {
  return [
    '# Auto-generated by bin/df-filter-suggest.js',
    'proposals:',
    `  - pattern: ${pattern}`,
    `    template: ${template}`,
    `    score: ${score.toFixed(4)}`,
    '    mode: auto',
    `    createdAt: ${new Date().toISOString()}`,
  ].join('\n') + '\n';
}

/**
 * Build a JSONL canary file with `count` rows for the given filterName.
 * All rows have signal_lost=false.
 */
function buildCanaryRows(filterName, count, signalLost = false) {
  const rows = [];
  for (let i = 0; i < count; i++) {
    rows.push(JSON.stringify({
      filter: filterName,
      raw_signal_tokens: 5,
      filtered_signal_tokens: 4,
      signal_lost: signalLost,
    }));
  }
  return rows.join('\n') + '\n';
}

/**
 * Run df-filter-suggest.js --promote with explicit paths via CLI flags.
 * Returns { stdout, stderr, code }.
 */
function runPromote({ canaryFile, outFile, cwd }) {
  const result = spawnSync(
    process.execPath,
    [
      SUGGEST_PATH,
      '--promote',
      '--canary', canaryFile,
      '--out', outFile,
    ],
    {
      cwd: cwd || WORKTREE_ROOT,
      encoding: 'utf8',
      timeout: 15_000,
      env: { ...process.env },
    }
  );
  return {
    stdout: result.stdout || '',
    stderr: result.stderr || '',
    code:   result.status ?? 1,
  };
}

// ---------------------------------------------------------------------------
// Test 1 — Latency delta: p95 with canary < p95 baseline + 5ms
// ---------------------------------------------------------------------------

describe('latency — canary overhead p95 < 5ms vs baseline', () => {
  let tmp;
  let canaryFile;

  before(() => {
    tmp = makeTmpDir();
    fs.mkdirSync(path.join(tmp, '.deepflow'), { recursive: true });
    canaryFile = path.join(tmp, '.deepflow', 'auto-filter-canary.jsonl');
  });

  after(() => rmrf(tmp));

  test('50-run p95 latency delta < 5ms', { timeout: 90_000 }, () => {
    const RUNS    = 50;
    const WARMUP  = 10;
    // Use a command that normalizes to 'git diff <ref>' — triggers canary lookup.
    const CMD = 'git diff HEAD~1';

    // Warm up the node module cache and OS fs-cache before measuring.
    // This prevents the canary-enabled phase from benefiting from cache
    // warm-up that occurred during the baseline phase.
    for (let i = 0; i < WARMUP; i++) measureHookMs(CMD, tmp);

    // Baseline: no proposals file present
    const baselineTimes = [];
    for (let i = 0; i < RUNS; i++) {
      baselineTimes.push(measureHookMs(CMD, tmp));
    }

    // Canary-enabled: write a matching proposal for 'git diff <ref>'
    const proposalYaml = buildProposalYaml('diff-stat-only', 'git diff <ref>', 100);
    fs.writeFileSync(path.join(tmp, '.deepflow', 'filters-proposed.yaml'), proposalYaml);

    const canaryTimes = [];
    for (let i = 0; i < RUNS; i++) {
      canaryTimes.push(measureHookMs(CMD, tmp));
    }

    const baselineP95 = p95(baselineTimes);
    const canaryP95   = p95(canaryTimes);
    const delta       = canaryP95 - baselineP95;

    // The canary runner uses spawn+unref (fire-and-forget / SPIKE-A pattern),
    // so its overhead on the hook return path should be well under 5ms.
    // On a loaded machine the p95 delta can fluctuate; 5ms is the spec limit.
    assert.ok(
      delta < 5,
      `p95 delta exceeded 5ms: baseline=${baselineP95.toFixed(2)}ms, canary=${canaryP95.toFixed(2)}ms, delta=${delta.toFixed(2)}ms`
    );
  });
});

// ---------------------------------------------------------------------------
// Test 2 — Promotion path: 20 clean rows → file copied to generated/
// ---------------------------------------------------------------------------

describe('promotion — 20 clean canary rows promote proposal', () => {
  let tmp;
  let canaryFile;
  let proposedFile;
  let promotedFile;

  // Check template exists — if not, tests cannot run meaningfully
  const FILTER_NAME = 'diff-stat-only';
  const TEMPLATE_SRC = path.join(TEMPLATES_DIR, `${FILTER_NAME}.js`);
  const templateExists = fs.existsSync(TEMPLATE_SRC);

  beforeEach(() => {
    tmp = makeTmpDir();
    canaryFile   = path.join(tmp, 'auto-filter-canary.jsonl');
    proposedFile = path.join(tmp, 'filters-proposed.yaml');
    promotedFile = path.join(GENERATED_DIR, `${FILTER_NAME}.js`);
  });

  afterEach(() => {
    // Clean up generated file if we created it
    if (fs.existsSync(promotedFile)) {
      try { fs.unlinkSync(promotedFile); } catch (_) {}
    }
    rmrf(tmp);
  });

  test('20 rows with signal_lost=false: proposal is promoted', { skip: !templateExists }, () => {
    // Seed canary JSONL with 20 clean rows
    fs.writeFileSync(canaryFile, buildCanaryRows(FILTER_NAME, 20, false));

    // Seed proposals YAML with a matching proposal
    // The promoteFilters() in df-filter-suggest reads 'template' as the archetype
    // and 'name' OR 'template' as the filter name (for canary lookup).
    const proposalYaml = buildProposalYaml(FILTER_NAME, 'git diff <ref>', 100);
    fs.writeFileSync(proposedFile, proposalYaml);

    const result = runPromote({
      canaryFile,
      outFile: proposedFile,
      cwd: WORKTREE_ROOT,
    });

    assert.equal(result.code, 0, `promote exited non-zero: ${result.stderr}`);

    // Generated file should exist
    assert.ok(
      fs.existsSync(promotedFile),
      `Expected generated file at ${promotedFile} — stdout: ${result.stdout} stderr: ${result.stderr}`
    );

    // Proposal should be removed from the YAML (either empty proposals list or pattern absent)
    const remaining = fs.readFileSync(proposedFile, 'utf8');
    assert.ok(
      !remaining.includes(`- pattern: git diff <ref>`),
      `Proposal still in yaml after promotion:\n${remaining}`
    );
  });

  test('20 rows with signal_lost=false: stdout confirms 1 promoted', { skip: !templateExists }, () => {
    fs.writeFileSync(canaryFile, buildCanaryRows(FILTER_NAME, 20, false));
    fs.writeFileSync(proposedFile, buildProposalYaml(FILTER_NAME, 'git diff <ref>', 100));

    const result = runPromote({ canaryFile, outFile: proposedFile, cwd: WORKTREE_ROOT });

    assert.ok(
      result.stdout.includes('1 promoted'),
      `Expected "1 promoted" in stdout: ${result.stdout}`
    );
  });
});

// ---------------------------------------------------------------------------
// Test 3 — Non-promotion: 19 rows → proposal stays unchanged
// ---------------------------------------------------------------------------

describe('non-promotion — 19 canary rows leave proposal in yaml', () => {
  let tmp;
  let canaryFile;
  let proposedFile;

  const FILTER_NAME = 'diff-stat-only';
  const TEMPLATE_SRC = path.join(TEMPLATES_DIR, `${FILTER_NAME}.js`);
  const templateExists = fs.existsSync(TEMPLATE_SRC);

  beforeEach(() => {
    tmp = makeTmpDir();
    canaryFile   = path.join(tmp, 'auto-filter-canary.jsonl');
    proposedFile = path.join(tmp, 'filters-proposed.yaml');
  });

  afterEach(() => {
    // Safety check: generated file must NOT have been created
    const promotedFile = path.join(GENERATED_DIR, `${FILTER_NAME}.js`);
    if (fs.existsSync(promotedFile)) {
      // Clean up in case something went wrong, but also fail loudly
      try { fs.unlinkSync(promotedFile); } catch (_) {}
    }
    rmrf(tmp);
  });

  test('19 rows: generated/ file does NOT exist', { skip: !templateExists }, () => {
    // Ensure generated file absent before test
    const promotedFile = path.join(GENERATED_DIR, `${FILTER_NAME}.js`);
    if (fs.existsSync(promotedFile)) fs.unlinkSync(promotedFile);

    fs.writeFileSync(canaryFile, buildCanaryRows(FILTER_NAME, 19, false));
    fs.writeFileSync(proposedFile, buildProposalYaml(FILTER_NAME, 'git diff <ref>', 100));

    const result = runPromote({ canaryFile, outFile: proposedFile, cwd: WORKTREE_ROOT });

    assert.equal(result.code, 0, `promote exited non-zero: ${result.stderr}`);
    assert.ok(
      !fs.existsSync(promotedFile),
      `Generated file should NOT exist with only 19 canary rows: ${promotedFile}`
    );
  });

  test('19 rows: proposal remains in filters-proposed.yaml', { skip: !templateExists }, () => {
    const promotedFile = path.join(GENERATED_DIR, `${FILTER_NAME}.js`);
    if (fs.existsSync(promotedFile)) fs.unlinkSync(promotedFile);

    fs.writeFileSync(canaryFile, buildCanaryRows(FILTER_NAME, 19, false));
    fs.writeFileSync(proposedFile, buildProposalYaml(FILTER_NAME, 'git diff <ref>', 100));

    runPromote({ canaryFile, outFile: proposedFile, cwd: WORKTREE_ROOT });

    const remaining = fs.readFileSync(proposedFile, 'utf8');
    assert.ok(
      remaining.includes('diff-stat-only'),
      `Proposal should still be in yaml with 19 rows:\n${remaining}`
    );
  });

  test('19 rows: stdout reports 0 promoted', { skip: !templateExists }, () => {
    const promotedFile = path.join(GENERATED_DIR, `${FILTER_NAME}.js`);
    if (fs.existsSync(promotedFile)) fs.unlinkSync(promotedFile);

    fs.writeFileSync(canaryFile, buildCanaryRows(FILTER_NAME, 19, false));
    fs.writeFileSync(proposedFile, buildProposalYaml(FILTER_NAME, 'git diff <ref>', 100));

    const result = runPromote({ canaryFile, outFile: proposedFile, cwd: WORKTREE_ROOT });

    assert.ok(
      result.stdout.includes('0 promoted'),
      `Expected "0 promoted" in stdout: ${result.stdout}`
    );
  });
});
