/**
 * Tests for AC-8 token budget enforcement (specs/codebase-map.md#AC-8)
 *
 * Shells out to `node bin/count-tokens.js` (cl100k_base tokenizer) to count
 * real tokens in:
 *   1. CLAUDE.md                    — must be ≤5 000 tokens
 *   2. .deepflow/codebase/ artifacts — summed must be 15 000–25 000 tokens
 *
 * When .deepflow/codebase/ does not yet exist (post-init, before /df:map has
 * run) the artifact-sum tests are skipped with a TODO note rather than failing,
 * because the directory is generated at runtime by the command.
 *
 * Uses Node.js built-in node:test — no extra dependencies.
 */

'use strict';

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

// ── Constants ────────────────────────────────────────────────────────────────

/** Project root: one level above hooks/ */
const REPO_ROOT = path.resolve(__dirname, '..');

/** Path to the token-counting script */
const COUNT_TOKENS_BIN = path.join(REPO_ROOT, 'bin', 'count-tokens.js');

/** CLAUDE.md token ceiling (AC-8) */
const CLAUDE_MD_MAX = 5000;

/** Artifact sum floor/ceiling (AC-8) */
const ARTIFACT_SUM_MIN = 15000;
const ARTIFACT_SUM_MAX = 25000;

/** Canonical artifact file names generated by /df:map */
const ARTIFACT_NAMES = [
  'STACK.md',
  'ARCHITECTURE.md',
  'CONVENTIONS.md',
  'STRUCTURE.md',
  'TESTING.md',
  'INTEGRATIONS.md',
];

/** Location where /df:map writes artifacts */
const CODEBASE_DIR = path.join(REPO_ROOT, '.deepflow', 'codebase');

// ── Helper ───────────────────────────────────────────────────────────────────

/**
 * Count cl100k_base tokens in a file by shelling out to count-tokens.js.
 *
 * @param {string} filePath - Absolute path to the file.
 * @returns {number} Token count.
 * @throws if count-tokens.js exits non-zero or output is not an integer.
 */
function countTokens(filePath) {
  const raw = execFileSync(
    process.execPath,
    [COUNT_TOKENS_BIN, filePath],
    { encoding: 'utf8', timeout: 10000 }
  ).trim();

  const n = parseInt(raw, 10);
  if (!Number.isFinite(n) || String(n) !== raw) {
    throw new Error(`count-tokens.js returned unexpected output: ${JSON.stringify(raw)}`);
  }
  return n;
}

// ── AC-8 part 1: bin/count-tokens.js exists and is callable ──────────────────

describe('AC-8 prerequisite: bin/count-tokens.js', () => {
  test('count-tokens.js exists at bin/count-tokens.js', () => {
    assert.ok(
      fs.existsSync(COUNT_TOKENS_BIN),
      `Expected count-tokens.js at ${COUNT_TOKENS_BIN}`
    );
  });

  test('count-tokens.js prints a positive integer for a small string via stdin', () => {
    const raw = execFileSync(
      process.execPath,
      [COUNT_TOKENS_BIN, '-'],
      { input: 'hello world', encoding: 'utf8', timeout: 5000 }
    ).trim();
    const n = parseInt(raw, 10);
    assert.ok(Number.isFinite(n) && n > 0, `Expected positive integer, got ${JSON.stringify(raw)}`);
  });

  test('count-tokens.js exits with error when file does not exist', () => {
    assert.throws(
      () =>
        execFileSync(
          process.execPath,
          [COUNT_TOKENS_BIN, '/does/not/exist/__abc__.md'],
          { encoding: 'utf8', timeout: 5000 }
        ),
      (err) => {
        assert.ok(err.status !== 0, 'Expected non-zero exit for missing file');
        return true;
      }
    );
  });
});

// ── AC-8 part 2: CLAUDE.md token ceiling ─────────────────────────────────────

describe('AC-8: CLAUDE.md must be ≤5 000 cl100k_base tokens', () => {
  const CLAUDE_MD_PATH = path.join(REPO_ROOT, 'CLAUDE.md');

  test('CLAUDE.md exists in repo root', () => {
    assert.ok(
      fs.existsSync(CLAUDE_MD_PATH),
      `Expected CLAUDE.md at ${CLAUDE_MD_PATH}`
    );
  });

  test(`CLAUDE.md token count ≤ ${CLAUDE_MD_MAX}`, () => {
    const tokens = countTokens(CLAUDE_MD_PATH);
    assert.ok(
      tokens <= CLAUDE_MD_MAX,
      `CLAUDE.md has ${tokens} tokens — exceeds ceiling of ${CLAUDE_MD_MAX}. ` +
      'Trim CLAUDE.md to keep it within the lazy-facts budget.'
    );
  });

  test('CLAUDE.md token count is a positive number (file is non-empty)', () => {
    const tokens = countTokens(CLAUDE_MD_PATH);
    assert.ok(tokens > 0, `CLAUDE.md appears empty (0 tokens)`);
  });
});

// ── AC-8 part 3: artifact sum 15k–25k (skipped when codebase dir absent) ─────

describe('AC-8: .deepflow/codebase/ artifact token sum must be 15 000–25 000', () => {
  // covers specs/codebase-map.md#AC-8
  const codemapExists = fs.existsSync(CODEBASE_DIR);

  if (!codemapExists) {
    // Post-init state: /df:map has not run yet — skip but leave a TODO marker
    test.todo(
      '.deepflow/codebase/ does not exist yet — run /df:map to generate artifacts, ' +
      'then re-run this test to verify the 15k–25k summed token budget'
    );
  } else {
    // Codebase map artifacts exist — verify the token budget

    /**
     * Collect all artifact files that exist under CODEBASE_DIR.
     * Returns [{ name, path, tokens }] for each present artifact.
     */
    function collectArtifactTokens() {
      return ARTIFACT_NAMES
        .map((name) => {
          const p = path.join(CODEBASE_DIR, name);
          return fs.existsSync(p)
            ? { name, path: p, tokens: countTokens(p) }
            : null;
        })
        .filter(Boolean);
    }

    test('at least one canonical artifact file exists under .deepflow/codebase/', () => {
      const found = ARTIFACT_NAMES.filter((n) => fs.existsSync(path.join(CODEBASE_DIR, n)));
      assert.ok(
        found.length > 0,
        `Expected at least one of [${ARTIFACT_NAMES.join(', ')}] in ${CODEBASE_DIR}`
      );
    });

    test(`summed artifact tokens are ≥ ${ARTIFACT_SUM_MIN}`, () => {
      const artifacts = collectArtifactTokens();
      const total = artifacts.reduce((s, a) => s + a.tokens, 0);
      const breakdown = artifacts.map((a) => `${a.name}=${a.tokens}`).join(', ');
      assert.ok(
        total >= ARTIFACT_SUM_MIN,
        `Artifact token sum is ${total} — below floor of ${ARTIFACT_SUM_MIN}. ` +
        `Breakdown: ${breakdown}. Artifacts may be too sparse; enrich their content.`
      );
    });

    test(`summed artifact tokens are ≤ ${ARTIFACT_SUM_MAX}`, () => {
      const artifacts = collectArtifactTokens();
      const total = artifacts.reduce((s, a) => s + a.tokens, 0);
      const breakdown = artifacts.map((a) => `${a.name}=${a.tokens}`).join(', ');
      assert.ok(
        total <= ARTIFACT_SUM_MAX,
        `Artifact token sum is ${total} — exceeds ceiling of ${ARTIFACT_SUM_MAX}. ` +
        `Breakdown: ${breakdown}. Artifacts are too verbose; trim them.`
      );
    });

    test('each individual artifact is non-empty (> 0 tokens)', () => {
      const artifacts = collectArtifactTokens();
      for (const a of artifacts) {
        assert.ok(
          a.tokens > 0,
          `Artifact ${a.name} has 0 tokens — must be non-empty per AC-8 "Body non-empty" rule`
        );
      }
    });

    test('no single artifact dominates (individual < 80% of ceiling)', () => {
      // Guard against a single bloated artifact consuming the entire budget.
      // 80% of 25k = 20k per artifact max.
      const singleMax = Math.floor(ARTIFACT_SUM_MAX * 0.8);
      const artifacts = collectArtifactTokens();
      for (const a of artifacts) {
        assert.ok(
          a.tokens < singleMax,
          `Artifact ${a.name} alone has ${a.tokens} tokens — ` +
          `exceeds 80% of the 25k ceiling (${singleMax}). This artifact is too large.`
        );
      }
    });
  }
});
